version: '3.9'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target:
        dev # <-- builds the "dev" stage from Dockerfile
        # In dev stage, we install all dependencies (including devDependencies)
        # This ensures the Nest CLI (needed for `npm run start:dev`) is available
        # Without this, Docker would build the production stage, which only has production deps
        # and running `npm run start:dev` would fail with "nest: not found"
    volumes:
      - .:/usr/src/app # Mount code for hot reload
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ./apps/api-gateway/.env
    command: npm run start:dev

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'
    env_file:
      - ./apps/user/.env
    command: npm run start:dev user

  media:
    build:
      context: .
      dockerfile: ./apps/media/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3010:3010'
    env_file:
      - ./apps/media/.env
    command: npm run start:dev media

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '3089:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api-gateway
    # networks:
    #   - backend

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    environment:
      SERVICES: >
        s3,
        sqs,
        sns,
        lambda,
        dynamodb
      DEBUG: 1
      DATA_DIR: /var/lib/localstack
      LAMBDA_EXECUTOR: docker
    ports:
      - '4566:4566' # Main LocalStack gateway
      - '4571:4571' # Lambda legacy port
    volumes:
      - './localstack:/etc/localstack' # optional config/scripts
      - '/var/run/docker.sock:/var/run/docker.sock' # needed for Lambda
      - 'localstack_data:/var/lib/localstack' # persistent LocalStack data

  # property:
  #   build:
  #     context: .
  #     dockerfile: ./apps/property/Dockerfile
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '3007:3007'
  #   env_file:
  #     - ./apps/property/.env
  #   command: npm run start:dev property

  # booking:
  #   build:
  #     context: .
  #     dockerfile: ./apps/booking/Dockerfile
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '3008:3008'
  #   env_file:
  #     - ./apps/booking/.env
  #   command: npm run start:dev booking
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3005:3005' # Only needs to map HTTP Port
    env_file:
      - ./apps/auth/.env
    command: npm run start:dev auth

  user-db-container-service:
    image: postgres:14
    env_file:
      - ./envs/user_db.env
    ports:
      - '5433:5432' #port mapping here is technically unnecesary as we dont connect to the db via the host machine anywhere. all conenctions are through docker containers (services and pgadmin are both containers) so we dont need to conenct via host machine
    volumes:
      - user-db-container-volume:/var/lib/postgresql/data
  
  media-db-container-service:
    image: postgres:14
    env_file:
      - ./envs/media_db.env
    ports:
      - '5434:5432' #port mapping here is technically unnecesary as we dont connect to the db via the host machine anywhere. all conenctions are through docker containers (services and pgadmin are both containers) so we dont need to conenct via host machine
    volumes:
      - media-db-container-volume:/var/lib/postgresql/data

  video-worker:
    build:
      context: ./workers/video-worker
    volumes:
    - ./workers/video-worker:/app   # mount source for hot reload
    - /usr/src/app/node_modules  
    depends_on:
      - localstack
    command: npx ts-node-dev --respawn src/index.ts


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '5052:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - user-db-container-service
      - media-db-container-service

  # localstack:
  #   container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
  #   image: localstack/localstack
  #   ports:
  #     - "127.0.0.1:4566:4566"            # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  #   environment:
  #     SERVICES: >
  #       s3,
  #       sqs,
  #       sns,
  #       lambda,
  #       dynamodb
  #     DEBUG: ${DEBUG:-0}
  #     DATA_DIR: /var/lib/localstack
  #     LAMBDA_EXECUTOR: docker
  #   volumes:
  #     - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  user-db-container-volume:
  media-db-container-volume:
  localstack_data:

